---
abstract: 'Convert vFiles into equivalent XML'
author:
  - 'Darren Kulp, C<< <kulp at cpan.org> >>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.133380'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text-vFile-toXML
no_index:
  directory:
    - t
    - inc
requires:
  Test::More: 0.42
  Text::vFile::asData: 0
  XML::Quick: 0
  XML::SemanticDiff: 0
version: 0.05
